;===== string constants for the program: ======
str0 db  'Enter 1 and press <return> to start: ',0
str1 db  'Invalid input...Enter 1 and press <return> to start: ',0
str2 db  '42+7-31+1:           should be 19:          ',0
str3 db  'good * little:       should be 15:          ',0
str4 db  '42000 DIV 4200:      should be 10:          ',0
str5 db  '42042 MOD 100:       should be 42:          ',0
str6 db  '20000 * 21000:       should be 420,000,000: ',0
str7 db  '6*7+2*little-1:      should be 47:          ',0
str8 db  '6*2+((1+2)*3-1)*2:   should be 28:          ',0
str9 db  'IF test:             should be  4:          ',0
str10 db  'IF test:             should be 17:          ',0
str11 db  'IF test:             should be 71:          ',0
str12 db  'AND test:            should be 21:          ',0
str13 db  'AND test:            should be 22:          ',0
str14 db  'OR test:             should be 23:          ',0
str15 db  'OR test:             should be 24:          ',0
str16 db  'OR AND test:         should be 25:          ',0
str17 db  'LOOP test:           should be 1-9:        ',0
str18 db  'LOOP test:           should be nice:       ',0
str19 db  '@',0
