;===== string constants for the program: ======
str0 db  'Testing expressions:',0
str1 db  '42+7-31+1: should be 19: ',0
str2 db  'good * lowest: should be 15: ',0
str3 db  '-good * lowest: should be -15: ',0
str4 db  '42000 DIV 4200: should be 10: ',0
str5 db  '42042 MOD 100: should be 42: ',0
str6 db  '20000 * 21000: should be 420,000,000: ',0
str7 db  '-20000 * 21000: should be -420,000,000: ',0
str8 db  '6*7+2*lowest-1: should be 47: ',0
str9 db  '6*2+((1+2)*3-1)*2: should be 28: ',0
