;===== string constants for the program: ======
str0 db  'Part 1:',0
str1 db  '_______',0
str2 db  '42+8-31+ugly:        should be 20:          ',0
str3 db  'good * little:       should be 15:          ',0
str4 db  '42000 DIV 4200:      should be 10:          ',0
str5 db  '42042 MOD 100:       should be 42:          ',0
str6 db  '20000 * 21000:       should be 420,000,000: ',0
str7 db  '6*7+2*little-1:      should be 47:          ',0
str8 db  '6*2+((1+2)*3-1)*2:   should be 28:          ',0
str9 db  'Enter 1 and press <return> to continue): ',0
str10 db  'Invalid input...Enter 1 and press <return> to continue: ',0
str11 db  'Part 2:',0
str12 db  '_______',0
str13 db  'IF test(5):          should be  4:          ',0
str14 db  'IF test(5.01):       should be 17:          ',0
str15 db  'IF test(5.02):       should be 71:          ',0
str16 db  'AND test(5.03):      should be  1:          ',0
str17 db  'AND test(5.04):      should be  1:          ',0
str18 db  'OR test(5.05):       should be  1:          ',0
str19 db  'OR test(5.06):       should be  1:          ',0
str20 db  'OR AND test(5.07):   should be  1:          ',0
str21 db  'OR AND test(5.08):   should be  1:          ',0
str22 db  'OR AND test(5.09):   should be  1:          ',0
str23 db  'NOT test(5.10):      should be  1:          ',0
str24 db  'NOT test(5.11):      should be  1:          ',0
str25 db  'Enter 1 and press <return> to continue): ',0
str26 db  'Invalid input...Enter 1 and press <return> to continue: ',0
str27 db  'Part 3: LOOP test (1-X)',0
str28 db  '_______________________',0
str29 db  'Enter X: ',0
str30 db  'Enter 1 and press <return> to continue): ',0
str31 db  'Invalid input...Enter 1 and press <return> to continue: ',0
str32 db  'Part 4: Nested LOOP test (pretty pyramid)',0
str33 db  '_________________________________________',0
str34 db  'Enter height of the pyramid: ',0
str35 db  '@',0
